version: "3"
services:
  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "27018:27107"
    networks:
      - default
    volumes:
      - ./backend/docker-volume/mongo-volume:/data/db
    environment:
      - MONGO_INITDB_DATABASE=InviHR
      - MONGO_INITDB_USER=InviTestAdmin
      - MONGO_INITDB_PASSWORD=Invi-123
      - MONGO_INITDB_CLUSTER=cluster0.fvqeigj

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - default
      - frontend
 
    environment:
      - APP_ENIVERONMENT=production
    env_file:
      - ./backend/.env
    tty: true
    stdin_open: true
    depends_on:
      - mongo
    ports:
      - "5000:5107"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - frontend

    # volumes: 
    #   - "/home/ashish/InviHR/frontend:/frontend"   
    depends_on:
      - backend
    ports:
      - "3000:3000"

networks:
  default:
    name: backend-network-mern-docker-boilerplate
  frontend:
    name: frontend-network-mern-docker-boilerplate